# Import the path and include functions for defining URL patterns
from django.urls import path, include

# Import DefaultRouter to automatically generate URLs for viewsets (API endpoints)
from rest_framework.routers import DefaultRouter

# Import local views module (where view functions/classes are defined)
from . import views

# Create an instance of DRF's DefaultRouter (used to register ViewSets later)
router = DefaultRouter()
# We'll add viewsets later when we implement the API (currently router is empty)

# Main list of URL patterns for this app
urlpatterns = [
    # Include any routes generated by the router (empty for now)
    path('', include(router.urls)),
]

# --- Simple API View for testing ---

# Import decorator to define function-based API views
from rest_framework.decorators import api_view

# Import Response to return JSON responses
from rest_framework.response import Response

# Define a simple GET API endpoint to test the API
@api_view(['GET'])  # Only allow GET requests
def api_root(request):
    # Return a JSON response with basic info
    return Response({
        'message': 'BookHub API is working!',  # Confirmation message
        'endpoints': {  # Example endpoints (not yet implemented)
            'books': '/api/books/',
            'authors': '/api/authors/',
        }
    })

# Add the test API endpoint to the urlpatterns
urlpatterns += [
    path('', api_root, name='api-root'),  # Root API route
]
